name: Bug Report
description: Create a report to help us fix a bug in Speakify
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **🤖 Want an AI to jumpstart this issue?**
        Click the [Open in Copilot Workspace](https://copilot-workspace.githubnext.com/) button at the top of this issue to automatically sketch out a plan and generate code for a PR.
        
        ---
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am seeing the following error...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How do we trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What system are you on?
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
  - type: input
    id: other-environment
    attributes:
      label: Other Environment Details
      description: List your browser, app version, node version, etc.
      placeholder: "e.g., Chrome 120, Node.js v20.5.0"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or paste error logs here to help explain your problem.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this hasn't already been reported.
          required: true
