name: Feature Request
description: Suggest an idea or new feature for Speakify
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **🤖 Want an AI to jumpstart this issue?**
        Click the [Open in Copilot Workspace](https://copilot-workspace.githubnext.com/) button at the top of this issue to automatically sketch out a plan and generate code for a PR.
        
        ---
        Thanks for taking the time to share your ideas for Speakify!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this feature hasn't already been requested.
          required: true
