name: Question
description: Ask a question about Speakify
title: "[QUESTION] "
labels: ["question"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
